### ISSUE TITLE
[O13K2] get date type columns from bigquery

### ISSUE THREAD

**Issue by kayemkim** [sktaiflow/skt#101]
gcp.bq_table_to_pandas 에서 date type 컬럼을 가져올 때 에러 발생함
'spark.sql.execution.arrow.enabled'를 false로 바꾸라는 메시지가 뜨는데 확인 필요

**Comment by onevirus** [comment]
bq 쪽 spark_session 생성할 때 false 로 하지 않나요 ?

**Comment by kayemkim** [comment]
> bq 쪽 spark_session 생성할 때 false 로 하지 않나요 ?

true로 설정되어있어요.

**Comment by kayemkim** [comment]
arrow disabled 함
#111
