### ISSUE TITLE
[O14K4] 비식별 처리대상과 방법을 제공하는 서비스 필요

### ISSUE THREAD

**Issue by onevirus** [sktaiflow/skt#210]
**문제**
지금은 시스템간 데이터 전송 시 어떤 컬럼을 어떻게 처리해야 하는지에 관한 정보가 소스코드에 하드코딩 되어 있습니다.
각 DAG 별로 중복되어 정의되어 있어, 한 쪽이 변경시 다른 쪽에 반영이 안되어 처리 기준이 이분화 될 수 있음.
스윙 실시간 연동에서도 비식별 처리가 필요.
어떤 정보들이 비식별 처리 되는지 한 눈에 보기 힘듬.

**해결 방안**
중앙에서 어떤 정보를 어떻게 처리할것인지 관리하는 서비스를 만들고,
각 작업들은 런타임에 서비스에 접근하여 비식별 처리 기준을 가져가서 처리한다.

첫번째 방법
1. (테이블, 컬럼) 이 어떤 종류의 민감 정보인지 정의: (ex. 서비스번호, 주소, 이메일, ...)
2. 각 민감 정보를 어떻게 처리 할지 정의: 서비스번호->hashing,  이름->#masking ...
의 2 단계로 관리

두번째 방법
(테이블, 컬럼)을 어떻게 처리할지 직접 정의

첫번째 방법은 초기 구현이 커지는 대신 나중에 특정 정보의 비식별 방식을 변경시 편리함

**Comment by Robert-sktai** [comment]
Metadata를 얻어오기 위해서 아래 내용을 추가로 부탁드립니다.
- Swing 테이블 매핑 컬럼 정보 (column id 포함)

**Comment by hanuerjang** [comment]
#226

Swing 기준 정보 테이블 메타 API 개발

비식별 정보
http://etl.sktai.io/v1/de_identification/table_name
: 해당 table 컬럼 중 Hash, Masking 대상 정보 제공

Swing 기분 정보 테이블 스키마
http://etl.sktai.io/v1/swing_table/table_name
: 해당 테이블의 column list, data type, position, description 제공

Bigtable Rowkey 정보
http://etl.sktai.io/v1/swing_rowkey/table_name
: bigtable 적재 시, 해당 테이블의 rowkey(해당 테이블의 pk, 서번이 포함될 경우 서번 우선순위) 순서 제공
