### ISSUE TITLE
[O14K4] ETL API에 ye_location 필드 추가

### ISSUE THREAD

**Issue by broooooooo** [sktaiflow/skt#238]
- 현재 ETL API에 모든 테이블은 DataLake -> Saturn에 적재한다고 가정
- GCP에 올라가는 테이블 중 YE 위치가 Saturn이 아닌 경우도 있음
- 이런 경우를 대비해 YE db위치, ye_location을 필드로 추가하고자 함

**Comment by hanuerjang** [comment]
@broooooooo 요거 추가 하실껀가요?

**Comment by broooooooo** [comment]
아 추가하신 필드로 요건이 만족 될거 같아요!
